spring:
  application:
    group: @project.groupId@
    name: @project.name@
    version: @project.version@
  jackson:
    deserialization:
      fail-on-unknown-properties: false

brokers:
  capital:
    api:
      url: https://demo-api-capital.backend-capital.com
      user:
        login: ${CAPITAL_API_USER}
        password: ${CAPITAL_API_PASSWORD}
        apiKey: ${CAPITAL_API_KEY}

axe-trader:
  enabled: true
  market:
    ohlc:
      epics: US500
      resolutions: MINUTE_5

logging:
  level:
    io.g3tech: trace
