from pathlib import Path

from engine.instruments import load_instruments, parse_market_details, write_instruments

DETAILS = {
    "instrument": {
        "epic": "TESTIDX",
        "name": "Test Index",
        "type": "INDICES",
        "currency": "USD",
        "lotSize": 1,
        "marginFactor": 5,
        "marginFactorUnit": "PERCENTAGE",
        "openingHours": {
            "mon": ["00:00 - 20:59:50", "21:05 - 00:00"],
            "tue": ["00:00 - 21:00"],
            "wed": [], "thu": [], "fri": [], "sat": [],
            "sun": ["22:00 - 00:00"],
            "zone": "UTC",
        },
        "overnightFee": {
            "longRate": -0.02,
            "shortRate": -0.001,
            "swapChargeTimestamp": 1789678800000,
            "swapChargeInterval": 1440,
        },
    },
    "dealingRules": {
        "minDealSize": {"unit": "POINTS", "value": 0.5},
        "minSizeIncrement": {"unit": "POINTS", "value": 0.1},
        "minStepDistance": {"unit": "POINTS", "value": 0.01},
    },
}


def test_parses_sizes_fees_and_hours():
    spec = parse_market_details(DETAILS)

    assert spec["epic"] == "TESTIDX"
    assert spec["currency"] == "USD"
    assert spec["lot_size"] == 1
    assert spec["margin_factor_pct"] == 5
    assert spec["min_deal_size"] == 0.5
    assert spec["size_increment"] == 0.1
    assert spec["min_step_distance"] == 0.01
    assert spec["overnight_fee"] == {
        "long_rate": -0.02,
        "short_rate": -0.001,
        "charge_time_utc": "21:00",
        "interval_minutes": 1440,
    }
    assert spec["opening_hours"]["mon"] == [[0, 1260], [1265, 1440]]
    assert spec["opening_hours"]["tue"] == [[0, 1260]]
    assert spec["opening_hours"]["sat"] == []
    assert spec["opening_hours"]["sun"] == [[1320, 1440]]


def test_round_trips_through_yaml(tmp_path: Path):
    path = tmp_path / "instruments.yaml"
    write_instruments(path, {"TESTIDX": parse_market_details(DETAILS)}, fetched_on="2026-09-17")

    loaded = load_instruments(path)

    assert loaded["TESTIDX"]["opening_hours"]["mon"] == [[0, 1260], [1265, 1440]]
    assert path.read_text().startswith("# Generated by engine.instruments on 2026-09-17")
