"""Fetch Capital.com market details into instruments.yaml, and load it back."""

from __future__ import annotations

import argparse
import math
from datetime import date, datetime, timezone
from pathlib import Path

import yaml

DAYS = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]
SCOPE = ["US500", "OIL_BRENT", "OIL_CRUDE", "NATURALGAS", "GOLD", "SILVER", "US100", "DE40", "UK100",
         "J225", "EURUSD", "GBPUSD", "USDJPY", "BTCUSD", "ETHUSD"]


def _minutes(text: str, *, is_end: bool) -> int:
    parts = [int(p) for p in text.strip().split(":")]
    hours, minutes = parts[0], parts[1]
    seconds = parts[2] if len(parts) > 2 else 0
    total = hours * 60 + minutes + (math.ceil(seconds / 60) if is_end else 0)
    if is_end and total == 0:
        return 1440
    return total


def _interval(text: str) -> list[int]:
    start, end = text.split(" - ")
    return [_minutes(start, is_end=False), _minutes(end, is_end=True)]


def parse_market_details(details: dict) -> dict:
    instrument = details["instrument"]
    rules = details["dealingRules"]
    fee = instrument["overnightFee"]
    if instrument["openingHours"].get("zone") != "UTC":
        raise ValueError(f"{instrument['epic']}: opening hours are not in UTC")
    charge = datetime.fromtimestamp(fee["swapChargeTimestamp"] / 1000, tz=timezone.utc)
    return {
        "epic": instrument["epic"],
        "name": instrument["name"],
        "type": instrument["type"],
        "currency": instrument["currency"],
        "lot_size": instrument["lotSize"],
        "margin_factor_pct": instrument["marginFactor"],
        "min_deal_size": rules["minDealSize"]["value"],
        "size_increment": rules["minSizeIncrement"]["value"],
        "min_step_distance": rules["minStepDistance"]["value"],
        "overnight_fee": {
            "long_rate": fee["longRate"],
            "short_rate": fee["shortRate"],
            "charge_time_utc": charge.strftime("%H:%M"),
            "interval_minutes": fee["swapChargeInterval"],
        },
        "opening_hours": {day: [_interval(t) for t in instrument["openingHours"].get(day, [])] for day in DAYS},
    }


def write_instruments(path: Path, specs: dict[str, dict], fetched_on: str) -> None:
    header = (f"# Generated by engine.instruments on {fetched_on} from the Capital.com demo API.\n"
              "# Do not edit by hand; re-run `python -m engine.instruments`.\n"
              "# opening_hours: UTC minutes-of-day, half-open [start, end), as Capital.com reported them on the\n"
              "# fetch date (current daylight-saving state).\n")
    path.write_text(header + yaml.safe_dump({"fetched_on": fetched_on, "instruments": specs}, sort_keys=True))


def load_instruments(path: Path) -> dict[str, dict]:
    return yaml.safe_load(path.read_text())["instruments"]


def main(argv: list[str] | None = None) -> None:
    from engine.capital import DemoClient

    parser = argparse.ArgumentParser(description="Fetch Capital.com market details into instruments.yaml")
    parser.add_argument("--env", type=Path, required=True, help="path to the .env with CAPITAL_API_* keys")
    parser.add_argument("--out", type=Path, default=Path(__file__).resolve().parents[1] / "instruments.yaml")
    parser.add_argument("epics", nargs="*", default=SCOPE)
    args = parser.parse_args(argv)

    client = DemoClient(args.env)
    specs = {epic: parse_market_details(client.get(f"/markets/{epic}")) for epic in args.epics}
    write_instruments(args.out, specs, fetched_on=date.today().isoformat())
    print(f"wrote {len(specs)} instruments to {args.out}")


if __name__ == "__main__":
    main()
